services:
  - type: web
    name: grow-etf-model-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: CACHE_TTL
        value: "14400"
